[package]
name = "rust-postgres-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = [ "postgres", "runtime-tokio", "chrono" ] }
tokio = { version = "1.20.0", features = ["rt-multi-thread", "macros"]}
